"""notification destinations, subscriptions and outbox

Revision ID: 9cb3950eccff
Revises: d4a81c7f6b30
Create Date: 2026-07-28 10:00:00.000000+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9cb3950eccff'
down_revision: str | None = 'd4a81c7f6b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Same list-and-loop as the sync_events migration, for the same reason:
# `verify_rls_enforced()` refuses to boot if a readable table has no forced
# policy, so a table added to the models and forgotten here stops the deploy
# rather than quietly serving every agency's rows.
PROTECTED: list[tuple[str, str]] = [
    ("notification_destinations", "tenant_id"),
    ("notification_subscriptions", "tenant_id"),
    ("notification_link_tokens", "tenant_id"),
    ("notification_deliveries", "tenant_id"),
]

# Not tenant-scoped, and that is the point — see the model docstring. It still
# needs a forced policy, because the startup check is structural and will
# refuse to boot on any readable table without one.
GLOBAL_TABLES: list[str] = ["whatsapp_suppressions"]

SETTING = "app.tenant_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_suppressions',
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_hash')
    )
    op.create_table('notification_destinations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('address_encrypted', sa.Text(), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'address_hash', name='uq_destination_address')
    )
    op.create_index(op.f('ix_notification_destinations_tenant_id'), 'notification_destinations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_destinations_user_id'), 'notification_destinations', ['user_id'], unique=False)
    op.create_table('notification_link_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('address_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_notification_link_tokens_tenant_id'), 'notification_link_tokens', ['tenant_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('event_kind', sa.String(length=48), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['notification_destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_dedupe', 'notification_deliveries', ['destination_id', 'event_kind', 'subject_id'], unique=True, postgresql_where=sa.text('subject_id IS NOT NULL'))
    op.create_index('ix_deliveries_dest_kind_created', 'notification_deliveries', ['destination_id', 'event_kind', 'created_at'], unique=False)
    op.create_index('ix_deliveries_status_created', 'notification_deliveries', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('event_kind', sa.String(length=48), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['notification_destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'event_kind', name='uq_subscription_event')
    )
    op.create_index(op.f('ix_notification_subscriptions_destination_id'), 'notification_subscriptions', ['destination_id'], unique=False)
    op.create_index(op.f('ix_notification_subscriptions_tenant_id'), 'notification_subscriptions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    _enforce_rls()
    _touch_updated_at()


def _enforce_rls() -> None:
    for table, column in PROTECTED:
        # nullif is load-bearing: once set_config has run on a connection the
        # setting stays defined for that backend, so an unscoped transaction
        # reads back '' rather than NULL, and casting '' to uuid raises
        # instead of matching nothing.
        predicate = f"{column} = nullif(current_setting('{SETTING}', true), '')::uuid"
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING ({predicate})
            WITH CHECK ({predicate})
            """
        )

    for table in GLOBAL_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS global_read ON {table}")
        op.execute(f"CREATE POLICY global_read ON {table} USING (true) WITH CHECK (true)")


def _touch_updated_at() -> None:
    """Bind the existing trigger — these rows are written as raw SQL by
    workers holding no ORM object, so `Timestamps.updated_at`'s ORM-side
    `onupdate` never fires."""
    for table in [t for t, _ in PROTECTED] + GLOBAL_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_touch_updated_at ON {table}")
        op.execute(
            f"""
            CREATE TRIGGER {table}_touch_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_subscriptions_tenant_id'), table_name='notification_subscriptions')
    op.drop_index(op.f('ix_notification_subscriptions_destination_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_status_created', table_name='notification_deliveries')
    op.drop_index('ix_deliveries_dest_kind_created', table_name='notification_deliveries')
    op.drop_index('ix_deliveries_dedupe', table_name='notification_deliveries', postgresql_where=sa.text('subject_id IS NOT NULL'))
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_notification_link_tokens_tenant_id'), table_name='notification_link_tokens')
    op.drop_table('notification_link_tokens')
    op.drop_index(op.f('ix_notification_destinations_user_id'), table_name='notification_destinations')
    op.drop_index(op.f('ix_notification_destinations_tenant_id'), table_name='notification_destinations')
    op.drop_table('notification_destinations')
    op.drop_table('whatsapp_suppressions')
    # ### end Alembic commands ###
