"""ingestion tables

Creates the three tables the ingestion pipeline writes to (plan §8, §10), puts
each behind the same forced tenant policy the rest of the schema uses (§18),
adds an `updated_at` trigger, and adds `resolve_subscription()`.

`resolve_subscription` is the system's only pre-tenant read path. Graph change
notifications carry a message id and a subscription id and nothing else, and
the webhook that receives them is unauthenticated, so something has to map a
subscription to a tenant *before* any tenant context can exist. The alternative
— leaving `graph_subscriptions` outside RLS — would not even boot:
`verify_rls_enforced()` fails startup for any table the runtime role can read
without FORCE ROW LEVEL SECURITY, and it decides that structurally rather than
from a list of known tables. So the table keeps its policy and a SECURITY
DEFINER function takes one argument and returns three routing columns. A leak
there exposes routing ids, not mail.

Revision ID: f1efd83cfaba
Revises: 9b3e5d1c8a72
Create Date: 2026-07-27 06:57:11.921594+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.core.config import settings

# (table, column compared against app.tenant_id) — same shape as the original
# row_level_security migration, so the two read alike.
PROTECTED: list[tuple[str, str]] = [
    ("mailboxes", "tenant_id"),
    ("graph_subscriptions", "tenant_id"),
    ("email_messages", "tenant_id"),
]

SETTING = "app.tenant_id"


revision: str = 'f1efd83cfaba'
down_revision: str | None = '9b3e5d1c8a72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ms_user_id', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('folder_id', sa.String(length=256), nullable=False),
    sa.Column('folder_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('initial_sync_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backfill_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_months', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ms_user_id', 'folder_id', name='uq_mailbox_tenant_user_folder')
    )
    op.create_index(op.f('ix_mailboxes_tenant_id'), 'mailboxes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mailboxes_user_id'), 'mailboxes', ['user_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('graph_message_id', sa.Text(), nullable=False),
    sa.Column('internet_message_id', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.String(length=256), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('body_r2_key', sa.Text(), nullable=True),
    sa.Column('body_html_r2_key', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('source_state', sa.String(length=24), server_default='present', nullable=False),
    sa.Column('classification_status', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('classification_model', sa.String(length=128), nullable=True),
    sa.Column('classification_version', sa.String(length=32), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'mailbox_id', 'graph_message_id', name='uq_email_mailbox_graph_id'),
    sa.UniqueConstraint('tenant_id', 'mailbox_id', 'internet_message_id', name='uq_email_mailbox_internet_id')
    )
    op.create_index(op.f('ix_email_messages_mailbox_id'), 'email_messages', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_email_messages_processing_status'), 'email_messages', ['processing_status'], unique=False)
    op.create_index(op.f('ix_email_messages_received_datetime'), 'email_messages', ['received_datetime'], unique=False)
    op.create_index(op.f('ix_email_messages_retention_until'), 'email_messages', ['retention_until'], unique=False)
    op.create_index('ix_email_messages_stalled', 'email_messages', ['processing_status', 'updated_at'], unique=False, postgresql_where=sa.text("processing_status IN ('pending', 'fetched', 'classifying', 'extracting')"))
    op.create_index(op.f('ix_email_messages_tenant_id'), 'email_messages', ['tenant_id'], unique=False)
    op.create_table('graph_subscriptions',
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('client_state', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_index(op.f('ix_graph_subscriptions_mailbox_id'), 'graph_subscriptions', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_graph_subscriptions_tenant_id'), 'graph_subscriptions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    _apply_rls()
    _touch_updated_at()
    _create_resolver()


def _apply_rls() -> None:
    """Put every new table behind the tenant policy.

    No GRANT is issued: the row_level_security migration set ALTER DEFAULT
    PRIVILEGES for the app role, so tables created here inherit DML rights
    automatically. RLS is *not* inherited that way, which is exactly why
    forgetting this call would leave the tables readable and unprotected.
    """
    for table, column in PROTECTED:
        # nullif is load-bearing — see the original migration. Once set_config
        # has run on a connection the setting stays defined for that backend,
        # so an unscoped transaction reads back '' rather than NULL, and
        # casting '' to uuid raises instead of matching nothing.
        predicate = f"{column} = nullif(current_setting('{SETTING}', true), '')::uuid"
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING ({predicate})
            WITH CHECK ({predicate})
            """
        )


def _touch_updated_at() -> None:
    """Maintain `updated_at` in the database, not just in the ORM.

    `Timestamps.updated_at` uses SQLAlchemy's `onupdate`, which only fires for
    ORM flushes. Every write in the ingestion pipeline is raw SQL — the webhook
    must answer in under three seconds and the jobs run without the ORM — so
    `updated_at` would keep its insert-time value forever.

    That is not cosmetic. `rescan_stuck` decides what to requeue by how old
    `updated_at` is, so a row that had just advanced would still look stalled,
    be requeued immediately, and go round again — burning attempts until it
    failed. The one column nobody writes explicitly is the one the recovery
    layer trusts most.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION touch_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    for table, _ in PROTECTED:
        op.execute(
            f"""
            CREATE TRIGGER {table}_touch_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
            """
        )


def _create_resolver() -> None:
    """The one pre-tenant read path, deliberately narrow.

    SECURITY DEFINER runs as the migration role, which bypasses RLS, so the
    body must expose exactly the three routing columns and nothing else.
    search_path is pinned so the function cannot be tricked into resolving
    `graph_subscriptions` to an attacker-created table on a poisoned path.

    Retired subscriptions are excluded: a replaced or revoked subscription must
    stop routing, or notifications for a dead subscription keep resolving to a
    live mailbox.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION resolve_subscription(p_subscription_id text)
        RETURNS TABLE (tenant_id uuid, mailbox_id uuid, client_state text)
        LANGUAGE sql
        SECURITY DEFINER
        SET search_path = public, pg_temp
        AS $$
            SELECT s.tenant_id, s.mailbox_id, s.client_state
            FROM graph_subscriptions s
            WHERE s.subscription_id = p_subscription_id
              AND s.status = 'active'
        $$
        """
    )
    # Postgres grants EXECUTE to PUBLIC by default, which would make the GRANT
    # below decorative and hand this RLS-bypassing function to every role that
    # can connect. Revoke first, then grant deliberately.
    op.execute("REVOKE ALL ON FUNCTION resolve_subscription(text) FROM PUBLIC")
    op.execute(
        "GRANT EXECUTE ON FUNCTION resolve_subscription(text) "
        f'TO "{settings.DATABASE_APP_ROLE}"'
    )


def downgrade() -> None:
    # Functions first: dropping the tables would leave both pointing at nothing.
    op.execute("DROP FUNCTION IF EXISTS resolve_subscription(text)")
    for table, _ in PROTECTED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_touch_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS touch_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_subscriptions_tenant_id'), table_name='graph_subscriptions')
    op.drop_index(op.f('ix_graph_subscriptions_mailbox_id'), table_name='graph_subscriptions')
    op.drop_table('graph_subscriptions')
    op.drop_index(op.f('ix_email_messages_tenant_id'), table_name='email_messages')
    op.drop_index('ix_email_messages_stalled', table_name='email_messages', postgresql_where=sa.text("processing_status IN ('pending', 'fetched', 'classifying', 'extracting')"))
    op.drop_index(op.f('ix_email_messages_retention_until'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_received_datetime'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_processing_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_mailbox_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_mailboxes_user_id'), table_name='mailboxes')
    op.drop_index(op.f('ix_mailboxes_tenant_id'), table_name='mailboxes')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
