"""extraction tables

Revision ID: a020a3b90f54
Revises: 498eaa862e4f
Create Date: 2026-07-27 12:16:51.008049+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a020a3b90f54'
down_revision: str | None = '498eaa862e4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table created here, with the column that scopes it. The list is the
# whole point: `verify_rls_enforced()` refuses to start the app if a table
# carrying `tenant_id` has no policy, so a table added to the models and
# forgotten here does not quietly become readable across agencies — it stops
# the deployment.
#
# These four hold the most sensitive data in the product. An opportunity is one
# agency's live vacancy, and `extraction_evidence` quotes the source email
# verbatim.
PROTECTED: list[tuple[str, str]] = [
    ("opportunities", "tenant_id"),
    ("extractions", "tenant_id"),
    ("extraction_evidence", "tenant_id"),
    ("opportunity_field_overrides", "tenant_id"),
]

SETTING = "app.tenant_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_email_message_id'), 'extractions', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_extractions_tenant_id'), 'extractions', ['tenant_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('received_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_name_raw', sa.Text(), nullable=True),
    sa.Column('company_name_normalized', sa.Text(), nullable=True),
    sa.Column('job_title_raw', sa.Text(), nullable=True),
    sa.Column('job_title_normalized', sa.Text(), nullable=True),
    sa.Column('job_family', sa.String(length=64), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('work_arrangement', sa.String(length=32), nullable=True),
    sa.Column('working_hours_raw', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=16), nullable=True),
    sa.Column('salary_raw', sa.Text(), nullable=True),
    sa.Column('duration_raw', sa.Text(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('location_normalized', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('quality_state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_name_normalized'), 'opportunities', ['company_name_normalized'], unique=False)
    op.create_index(op.f('ix_opportunities_email_message_id'), 'opportunities', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_opportunities_job_title_normalized'), 'opportunities', ['job_title_normalized'], unique=False)
    op.create_index(op.f('ix_opportunities_location_normalized'), 'opportunities', ['location_normalized'], unique=False)
    op.create_index(op.f('ix_opportunities_received_datetime'), 'opportunities', ['received_datetime'], unique=False)
    op.create_index(op.f('ix_opportunities_review_status'), 'opportunities', ['review_status'], unique=False)
    op.create_index(op.f('ix_opportunities_tenant_id'), 'opportunities', ['tenant_id'], unique=False)
    op.create_table('extraction_evidence',
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_evidence_extraction_id'), 'extraction_evidence', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extraction_evidence_opportunity_id'), 'extraction_evidence', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_extraction_evidence_tenant_id'), 'extraction_evidence', ['tenant_id'], unique=False)
    op.create_table('opportunity_field_overrides',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('ai_value', sa.Text(), nullable=True),
    sa.Column('human_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_field_overrides_opportunity_id'), 'opportunity_field_overrides', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_field_overrides_tenant_id'), 'opportunity_field_overrides', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    _enforce_rls()
    _touch_updated_at()


def _touch_updated_at() -> None:
    """Attach the existing trigger to these tables too.

    `Timestamps.updated_at` only fires on an ORM flush, and the extraction
    pipeline writes through raw SQL for the same reason the ingestion one does.
    The function already exists from the ingestion migration; this only binds
    it, so an extraction row's `updated_at` means what every other table's
    means.
    """
    for table, _column in PROTECTED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_touch_updated_at ON {table}")
        op.execute(
            f"""
            CREATE TRIGGER {table}_touch_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
            """
        )


def _enforce_rls() -> None:
    """The same policy the ingestion tables carry, for the same reasons.

    FORCE, not merely ENABLE: without it the table owner bypasses the policy,
    and the owner is who migrations and any superuser session connect as — so
    an ENABLE-only table looks protected in the catalogue and is not.
    """
    for table, column in PROTECTED:
        # nullif is load-bearing — see the original migration. Once set_config
        # has run on a connection the setting stays defined for that backend,
        # so an unscoped transaction reads back '' rather than NULL, and
        # casting '' to uuid raises instead of matching nothing.
        predicate = f"{column} = nullif(current_setting('{SETTING}', true), '')::uuid"
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING ({predicate})
            WITH CHECK ({predicate})
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_field_overrides_tenant_id'), table_name='opportunity_field_overrides')
    op.drop_index(op.f('ix_opportunity_field_overrides_opportunity_id'), table_name='opportunity_field_overrides')
    op.drop_table('opportunity_field_overrides')
    op.drop_index(op.f('ix_extraction_evidence_tenant_id'), table_name='extraction_evidence')
    op.drop_index(op.f('ix_extraction_evidence_opportunity_id'), table_name='extraction_evidence')
    op.drop_index(op.f('ix_extraction_evidence_extraction_id'), table_name='extraction_evidence')
    op.drop_table('extraction_evidence')
    op.drop_index(op.f('ix_opportunities_tenant_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_review_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_received_datetime'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_location_normalized'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_job_title_normalized'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_email_message_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_name_normalized'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_extractions_tenant_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_email_message_id'), table_name='extractions')
    op.drop_table('extractions')
    # ### end Alembic commands ###
