"""early access signups

Revision ID: 8bbbf30a6292
Revises: 9c1f4a2b7e30
Create Date: 2026-07-26 18:28:42.016677+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8bbbf30a6292'
down_revision: str | None = '9c1f4a2b7e30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_access_signups',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Insert-only under FORCE RLS. The landing form is public and
    # unauthenticated, so the app role must be able to record a signup and
    # nothing more — with no SELECT policy, reads return zero rows even to the
    # code that wrote them, so a bug there cannot enumerate prospects. This
    # also satisfies the deny-by-default gate in app/db/rls.py, which refuses
    # to boot if any readable table lacks FORCE RLS.
    op.execute("ALTER TABLE early_access_signups ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE early_access_signups FORCE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS signup_insert_only ON early_access_signups")
    op.execute(
        "CREATE POLICY signup_insert_only ON early_access_signups "
        "FOR INSERT WITH CHECK (true)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('early_access_signups')
    # ### end Alembic commands ###
